import AppShell from "@/components/layout/AppShell";
import { Card, CardContent } from "@/components/common/Card";
import { 
  Zap, 
  ShieldCheck, 
  Brain, 
  Lock, 
  Target,
  Cpu,
  Fingerprint
} from "lucide-react";

/**
 * About Page Design:
 * - Informational Hierarchy: Clearly explains the 'Why' and 'How' of the system.
 * - Technical Authority: Uses deterministic language and high-contrast visuals.
 * - Mobile-First: Card-based layout optimized for quick scrolling and high legibility.
 */

export default function AboutPage() {
  return (
    <AppShell title="System Info">
      <div className="py-6 space-y-10 animate-in fade-in slide-in-from-bottom-2 duration-500">
        
        {/* Brand Mission */}
        <section className="px-1 space-y-4">
          <div className="w-12 h-12 bg-slate-900 rounded-2xl flex items-center justify-center text-white shadow-xl shadow-slate-200">
            <Zap size={24} fill="currentColor" className="text-blue-500" />
          </div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            Creator AI <br/>
            <span className="text-blue-600">Identity Engine</span>
          </h2>
          <p className="text-sm font-semibold text-slate-700 leading-relaxed">
            Creator AI is an agentic platform designed for professionals who need to scale 
            their content production without sacrificing their unique vocal identity.
          </p>
        </section>

        {/* The Digital Twin Concept */}
        <section className="space-y-4">
          <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.2em] px-1 flex items-center gap-2">
            <Fingerprint size={14} className="text-slate-900" /> The Digital Twin
          </h3>
          <Card>
            <CardContent className="p-6 space-y-4">
              <p className="text-sm font-medium text-slate-700 leading-relaxed">
                Unlike generic LLMs, our system builds a deterministic 
                <span className="text-slate-900 font-bold"> Vocal Identity</span>. 
                This identity acts as the single source of truth for every script, 
                hook, and caption generated by the engine.
              </p>
            </CardContent>
          </Card>
        </section>

        {/* The Memory Model */}
        <section className="space-y-4">
          <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.2em] px-1 flex items-center gap-2">
            <Brain size={14} className="text-slate-900" /> Memory Layers
          </h3>
          <div className="grid gap-3">
            <div className="flex gap-4 p-5 bg-white border border-slate-100 rounded-2xl shadow-sm">
              <div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center text-blue-600 flex-none">
                <Target size={20} strokeWidth={2.5} />
              </div>
              <div className="space-y-1">
                <p className="font-black text-xs text-slate-900 uppercase tracking-tight">Persona</p>
                <p className="text-[11px] font-semibold text-slate-500 leading-snug">Who you are. Your tone, dialect, and natural rhythm.</p>
              </div>
            </div>

            <div className="flex gap-4 p-5 bg-white border border-slate-100 rounded-2xl shadow-sm">
              <div className="w-10 h-10 bg-slate-50 rounded-xl flex items-center justify-center text-slate-900 flex-none">
                <ShieldCheck size={20} strokeWidth={2.5} />
              </div>
              <div className="space-y-1">
                <p className="font-black text-xs text-slate-900 uppercase tracking-tight">Preferences</p>
                <p className="text-[11px] font-semibold text-slate-500 leading-snug">Your intent. Strict production rules and creative constraints.</p>
              </div>
            </div>

            <div className="flex gap-4 p-5 bg-white border border-slate-100 rounded-2xl shadow-sm">
              <div className="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center text-emerald-600 flex-none">
                <Cpu size={20} strokeWidth={2.5} />
              </div>
              <div className="space-y-1">
                <p className="font-black text-xs text-slate-900 uppercase tracking-tight">Feedback</p>
                <p className="text-[11px] font-semibold text-slate-500 leading-snug">Continuous learning. Every edit improves the core model.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Security / Agentic Isolation */}
        <section className="space-y-4">
          <h3 className="text-[10px] font-black uppercase text-slate-400 tracking-[0.2em] px-1 flex items-center gap-2">
            <Lock size={14} className="text-slate-900" /> Architecture
          </h3>
          <Card className="bg-slate-900 border text-white overflow-hidden relative">
            <CardContent className="p-8 space-y-4 relative z-10">
              <h4 className="text-lg font-bold text-slate-700 leading-tight">Agentic Isolation Layer</h4>
              <p className="text-xs font-medium text-slate-400 leading-relaxed">
                Our AI agents are strictly decoupled from the data layer. They operate in 
                ephemeral execution environments, ensuring that your raw data is never 
                leaked to the LLM during the creative process.
              </p>
              <div className="pt-2 flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                <span className="text-[9px] font-black uppercase tracking-[0.2em] text-emerald-500">
                  Protocol Active
                </span>
              </div>
            </CardContent>
          </Card>
        </section>

        {/* Version / Credits */}
        <footer className="py-12 text-center space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-slate-100 rounded-full">
            <span className="w-2 h-2 rounded-full bg-slate-900" />
            <span className="text-[10px] font-black text-slate-900 uppercase tracking-widest">
              Creator AI Identity Engine v1.0.4
            </span>
          </div>
          <p className="text-[9px] font-bold text-slate-300 uppercase tracking-[0.4em]">
            Built for Professionals • Agentic First
          </p>
        </footer>

      </div>
    </AppShell>
  );
}